### ISSUE TITLE
Upload files in bill

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/E-Bill#115]

**Comment by zupzup** [comment]
Notes:
* PDF and image formats (png, jpg)
* new `./files` folder, with subfolder of bill ID including the files
  * maybe constraints for the file name (no spaces, utf-8)
* new event in DHT for sending/receiving files for bill-members (like get-bills/get-keys) - we need `get-attachments`
* new multipart/upload endpoint to upload files
* File upload will be re-used for identity/company image upload
