### ISSUE TITLE
Migrate critical code paths to use Rust Result error handling

### ISSUE THREAD

**Issue by tompro** [BitcreditProtocol/E-Bill#138]
A lot of critical execution is running with .unwrap() or .expect("msg"). Migrating some code to use Result<Err, T> 
and some library like thiserror and anyhow might make the app more stable.

**Comment by Nathan-Bransby-NMT** [comment]
@mtbitcr I will work on these changes now

**Comment by zupzup** [comment]
All relevant code has error handling now

**Comment by mtbitcr** [comment]
Hi @Nathan-Bransby-NMT, can you please send me your taproot address for e-IOU tokens.

**Comment by Nathan-Bransby-NMT** [comment]
> Hi @Nathan-Bransby-NMT, can you please send me your taproot address for e-IOU tokens.

bc1plfxvvnnaunl2g7jxnv9w56wcwalpcqxapj4q3l20xq65vnaunk0qu3fyh5
