### ISSUE TITLE
Identity chain

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/E-Bill#140]
We must create company identity chain. Similar to bill chain. There we will put all operations from correct identity.

**Comment by zupzup** [comment]
Cases:

        * Create identity
            * data = identity + node id (encrypted with rsa key)
                * for proof of registration, hash
            * block has hash+time stamp, number etc. (same as in bill)
            * signed with secp master key
            * OperationCode => Create
        * Update identity
            * data 
                * field -> new value (e.g.: "postal address" => "Smithstreet 5", "zip code" => "1020")
            * signed with secp master key
            * OperationCode => Update
        * Sign bill as a person (only possible for Bill signers) -> happens any time I do a signing operation (Draw, Accept, Request to Accept, Request to Pay, Endorse, Sell, Mint)
            * data - bill id, block number, block hash, operation
            * signed with secp master key
            * OperationCode => SignPersonBill
        * Create company
            * data - company id, block hash of first block of company chain
            * signed with secp master key
            * OperationCode => CreateCompany
        * Add signatory / Remove signatory
            * data - company id, block number and hash of block in company chain, node id of person that's added/removed
            * signed with secp master key
            * OperationCode => AddSignatory/RemoveSignatory
