### ISSUE TITLE
Check Blockstream asynchronously

### ISSUE THREAD

**Issue by zupzup** [BitcreditProtocol/E-Bill#161]
When checking things on the Bitcoin blockchain, don't block the UI for the whole time, since this might take longer.

Option:
We could check it asynchronously in the background and send the last time we got updated data to the frontend, which can then show it (and maybe a spinner, which indicates that it's fetched currently)

**Comment by HubertusVIE** [comment]
Removing the block is a good idea. Probably we can check more selectively for old items.

**Comment by zupzup** [comment]
Duplicate
