### ISSUE TITLE
Consistent naming for peer id and bill id

### ISSUE THREAD

**Issue by zupzup** [BitcreditProtocol/E-Bill#243]
Throughout the whole code-base, rename `peer_id` to `node_id`and `bill_name` to `bill_id`

**Comment by mubarak23** [comment]
For names like this `save_peer_id`, should we rename it to something like `save_node_id` @zupzup

**Comment by zupzup** [comment]
> For names like this `save_peer_id`, should we rename it to something like `save_node_id` @zupzup

Yes, every mention of `peer_id` should be renamed to `node_id`.

**Comment by mubarak23** [comment]
@zupzup do i have also need to make these changes to the frontend code

**Comment by zupzup** [comment]
> @zupzup do i have also need to make these changes to the frontend code

@mubarak23 No, the frontend in this repo is deprecated, anywhere in `./src/` is important.

**Comment by mtbitcr** [comment]
@mubarak23 Thank you for your contribution! You will be rewarded with 500 tokens at the beginning of the next quarter.
