### ISSUE TITLE
Check Paid status of Bills waiting for payment asynchronously

### ISSUE THREAD

**Issue by zupzup** [BitcreditProtocol/E-Bill#258]
For each bill that's waiting for payment, check the payment state in the blockchain asynchronously every 10 minutes (block time) and update the bill's paid state accordingly

**Comment by mubarak23** [comment]
please can you explain further and also pointers to any specific part of the code that handle this. @zupzup

**Comment by zupzup** [comment]
@mubarak23 if you're looking for a ticket to contribute, I think https://github.com/BitcreditProtocol/E-Bill/issues/193 could be a good candidate
